// swift-tools-version:5.9
// Generated by scripts/build-engine-xcframework.sh — do not edit by hand.
import PackageDescription

let package = Package(
    name: "EngineNativeFFI",
    platforms: [ .iOS(.v15) ],
    products: [ .library(name: "EngineNative", targets: ["EngineNative"]) ],
    targets: [
        .binaryTarget(name: "EngineNativeFFI", path: "EngineNative.xcframework"),
        .target(name: "EngineNative", dependencies: ["EngineNativeFFI"], path: "Sources/EngineNative")
    ]
)
