//! Conformance: secp-native must reproduce every @bsv/sdk-generated vector in
//! fixtures/vectors.json BYTE-FOR-BYTE. This file is the PoC's proof artifact.
//!
//! Vectors were generated by scripts/gen-vectors.mjs against the PUBLISHED
//! @bsv/sdk@2.1.6 (the exact package bsv-browser locks) and cross-checked identical
//! against the TypeScript ts-sdk HEAD (2.1.8). Nothing real was signed —
//! all keys/messages are sha256-of-label synthetics.

use secp_native::*;
use serde::Deserialize;

#[derive(Deserialize)]
struct Vectors {
    sign: Vec<SignVector>,
    brc42: Vec<Brc42Vector>,
    ecdh: Vec<EcdhVector>,
    tweak: Vec<TweakVector>,
    recover: Vec<RecoverVector>,
    #[serde(rename = "tweakMul")]
    tweak_mul: Vec<TweakMulVector>,
    combine: Vec<CombineVector>,
    #[serde(rename = "schnorrAccept")]
    schnorr_accept: Vec<SchnorrAcceptVector>,
    #[serde(rename = "schnorrReject")]
    schnorr_reject: Vec<SchnorrRejectVector>,
    #[serde(rename = "batchSign")]
    batch_sign: Vec<BatchSignVector>,
    #[serde(rename = "batchVerify")]
    batch_verify: BatchVerifyVectors,
    #[serde(rename = "batchDerive")]
    batch_derive: BatchDeriveVector,
    uncompressed: UncompressedVector,
}

#[derive(Deserialize)]
struct BatchSignVector {
    privkey: String,
    msg32: String,
    der: String,
    pubkey: String,
}

#[derive(Deserialize)]
struct BatchVerifyVectors {
    valid: Vec<BatchVerifyVector>,
    corrupted: Vec<BatchVerifyVector>,
}

#[derive(Deserialize)]
struct BatchVerifyVector {
    msg32: String,
    der: String,
    pubkey: String,
    valid: bool,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct BatchDeriveVector {
    root: String,
    counterparty_priv: String,
    counterparty_pub: String,
    root_pub: String,
    invoice_numbers: Vec<String>,
    derived_privs: Vec<String>,
    derived_pubs_uncompressed: Vec<String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct UncompressedVector {
    privkey: String,
    pubkey: String,
    tweak: String,
    msg32: String,
    compact: String,
    pubkey_create: String,
    ecdh_shared_point: String,
    tweak_add: String,
    recovered: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct RecoverVector {
    #[allow(dead_code)]
    privkey: String,
    msg32: String,
    pubkey: String,
    recovery: u32,
    compact: String,
    recovered_all_factors: [Option<String>; 4],
}

#[derive(Deserialize)]
struct TweakMulVector {
    pubkey: String,
    scalar: String,
    result: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct CombineVector {
    pubkey_a: String,
    pubkey_b: String,
    result: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct SchnorrAcceptVector {
    a: String,
    #[allow(dead_code)]
    b: String,
    r: String,
    #[serde(rename = "A")]
    a_pub: String,
    #[serde(rename = "B")]
    b_pub: String,
    #[serde(rename = "S")]
    s: String,
    #[serde(rename = "R")]
    r_pub: String,
    #[serde(rename = "SPrime")]
    s_prime: String,
    e: String,
    z: String,
}

#[derive(Deserialize)]
struct SchnorrRejectVector {
    label: String,
    #[serde(rename = "A")]
    a_pub: String,
    #[serde(rename = "B")]
    b_pub: String,
    #[serde(rename = "S")]
    s: String,
    #[serde(rename = "R")]
    r_pub: String,
    #[serde(rename = "SPrime")]
    s_prime: String,
    z: String,
}

#[derive(Deserialize)]
struct SignVector {
    privkey: String,
    msg32: String,
    pubkey: String,
    der: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Brc42Vector {
    privkey: String,
    counterparty_pub: String,
    invoice_number: String,
    shared_point: String,
    hmac_tweak: String,
    derived_priv: String,
    derived_pub: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct EcdhVector {
    privkey: String,
    pubkey: String,
    shared_point: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct TweakVector {
    privkey: String,
    tweak: String,
    pubkey: String,
    priv_result: String,
    pub_result: String,
}

fn load() -> Vectors {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/vectors.json");
    serde_json::from_str(&std::fs::read_to_string(path).expect("fixtures/vectors.json"))
        .expect("parse vectors.json")
}

fn h(s: &str) -> Vec<u8> {
    hex::decode(s).unwrap()
}

/// Sign class: pubkey_create AND the DER signature must match the SDK byte-for-byte
/// (RFC 6979 nonces on both sides — see lib.rs header). Also proves verify-compat in
/// both directions: byte-equality makes "Rust sig verifies in SDK" identical to the
/// SDK self-verify already asserted at generation time, and we explicitly verify the
/// SDK's DER sig with Rust here.
#[test]
fn sign_vectors_exact_match() {
    let v = load();
    assert!(!v.sign.is_empty());
    for (i, t) in v.sign.iter().enumerate() {
        let pk = pubkey_create(h(&t.privkey)).unwrap();
        assert_eq!(hex::encode(&pk), t.pubkey, "sign[{i}] pubkey");
        let der = ecdsa_sign(h(&t.msg32), h(&t.privkey)).unwrap();
        assert_eq!(hex::encode(&der), t.der, "sign[{i}] DER (nonce/low-S mismatch?)");
        // SDK-produced sig verifies under Rust (redundant given byte-equality, kept
        // explicit so a future nonce divergence still leaves this compat assertion).
        assert!(ecdsa_verify(h(&t.msg32), h(&t.der), pk).unwrap(), "sign[{i}] verify SDK sig");
    }
}

/// BRC-42 class: shared point, HMAC tweak, derived privkey, derived pubkey — all
/// nonce-free, all byte-exact. Intermediates are asserted so a failure localizes.
#[test]
fn brc42_vectors_exact_match() {
    let v = load();
    assert!(!v.brc42.is_empty());
    for (i, t) in v.brc42.iter().enumerate() {
        let shared = ecdh_shared_point(h(&t.privkey), h(&t.counterparty_pub)).unwrap();
        assert_eq!(hex::encode(&shared), t.shared_point, "brc42[{i}] sharedPoint");
        let derived =
            brc42_derive_child(h(&t.privkey), h(&t.counterparty_pub), t.invoice_number.clone())
                .unwrap();
        assert_eq!(hex::encode(&derived), t.derived_priv, "brc42[{i}] derivedPriv");
        let derived_pub = pubkey_create(derived).unwrap();
        assert_eq!(hex::encode(&derived_pub), t.derived_pub, "brc42[{i}] derivedPub");
        // hmac tweak: recompute via privkey_tweak_add path equivalence:
        // derived == priv + hmacTweak (mod n)
        let via_tweak = privkey_tweak_add(h(&t.privkey), h(&t.hmac_tweak)).unwrap();
        assert_eq!(hex::encode(&via_tweak), t.derived_priv, "brc42[{i}] hmacTweak path");
        // and the PUBLIC side: counterpartyless pubkey_tweak_add(P, hmacTweak) == derivedPub
        let pub_side = pubkey_tweak_add(pubkey_create(h(&t.privkey)).unwrap(), h(&t.hmac_tweak))
            .unwrap();
        assert_eq!(hex::encode(&pub_side), t.derived_pub, "brc42[{i}] pubkey tweak path");
    }
}

/// ECDH class: compressed shared point byte-exact vs SDK deriveSharedSecret.
#[test]
fn ecdh_vectors_exact_match() {
    let v = load();
    assert!(!v.ecdh.is_empty());
    for (i, t) in v.ecdh.iter().enumerate() {
        let shared = ecdh_shared_point(h(&t.privkey), h(&t.pubkey)).unwrap();
        assert_eq!(hex::encode(&shared), t.shared_point, "ecdh[{i}]");
    }
}

/// secp256k1 field prime p minus group order n, as 32 BE bytes — the recid-2/3
/// asymmetry boundary (x = r + n overflows the field iff r >= p - n).
/// p - n = 0x14551231950b75fc4402da1722fc9baee (129 bits).
fn p_minus_n() -> [u8; 32] {
    let mut out = [0u8; 32];
    let tail = hex::decode("014551231950b75fc4402da1722fc9baee").unwrap();
    out[32 - tail.len()..].copy_from_slice(&tail);
    out
}

/// Recover class (issue #5): compact round-trip + recovery factor + per-recid
/// parity. recid 0/1 must match the SDK exactly (value ↔ value, null ↔ error).
/// recid 2/3: exact parity when r < p - n; otherwise the SDK reduces x = r + n
/// mod p (Point.fromX) and may fabricate a point while libsecp256k1 rejects the
/// field overflow — the native side MUST reject there (the app seam falls back
/// to pure JS, preserving SDK behavior; documented in src/lib.rs).
#[test]
fn recover_vectors_match() {
    let v = load();
    assert!(!v.recover.is_empty());
    let boundary = p_minus_n();
    for (i, t) in v.recover.iter().enumerate() {
        let compact = h(&t.compact);
        // full-compact recovery == the signing pubkey
        let pk = ecdsa_recover(h(&t.msg32), compact.clone()).unwrap();
        assert_eq!(hex::encode(&pk), t.pubkey, "recover[{i}] compact round-trip");
        // recovery factor search matches CalculateRecoveryFactor
        let rs64 = compact[1..].to_vec();
        let rec = ecdsa_recovery_factor(h(&t.msg32), rs64.clone(), h(&t.pubkey)).unwrap();
        assert_eq!(rec, t.recovery, "recover[{i}] recovery factor");
        // per-recid parity
        let r32: [u8; 32] = compact[1..33].try_into().unwrap();
        for recid in 0u8..4 {
            let mut c = vec![27 + 4 + recid];
            c.extend_from_slice(&rs64);
            let native = ecdsa_recover(h(&t.msg32), c);
            let sdk = &t.recovered_all_factors[recid as usize];
            if recid < 2 || r32 < boundary {
                match (sdk, native) {
                    (Some(exp), Ok(got)) => {
                        assert_eq!(hex::encode(got), *exp, "recover[{i}] recid {recid}")
                    }
                    (None, Err(_)) => {}
                    (s, n) => panic!(
                        "recover[{i}] recid {recid} parity broke: sdk={s:?} native_ok={}",
                        n.is_ok()
                    ),
                }
            } else {
                // documented asymmetry zone: native must reject the field overflow
                assert!(
                    native.is_err(),
                    "recover[{i}] recid {recid}: native accepted r + n >= p (must reject)"
                );
            }
        }
    }
}

/// tweakMul class (issue #5): t·P byte-exact vs SDK Point.mul.
#[test]
fn tweak_mul_vectors_exact_match() {
    let v = load();
    assert!(!v.tweak_mul.is_empty());
    for (i, t) in v.tweak_mul.iter().enumerate() {
        let out = pubkey_tweak_mul(h(&t.pubkey), h(&t.scalar)).unwrap();
        assert_eq!(hex::encode(&out), t.result, "tweakMul[{i}]");
    }
}

/// combine class (issue #5): A+B byte-exact vs SDK Point.add (incl. doubling).
#[test]
fn combine_vectors_exact_match() {
    let v = load();
    assert!(!v.combine.is_empty());
    for (i, t) in v.combine.iter().enumerate() {
        let out = pubkey_combine(h(&t.pubkey_a), h(&t.pubkey_b)).unwrap();
        assert_eq!(hex::encode(&out), t.result, "combine[{i}]");
    }
}

/// Schnorr accept class (issue #6): the challenge, the full generate output
/// (R ‖ S' ‖ z) and the verify verdict must all match the SDK byte-for-byte.
#[test]
fn schnorr_accept_vectors_exact_match() {
    let v = load();
    assert!(!v.schnorr_accept.is_empty());
    for (i, t) in v.schnorr_accept.iter().enumerate() {
        // challenge intermediate — localizes any hashing/serialization divergence
        let e = schnorr_challenge(
            &h(&t.a_pub), &h(&t.b_pub), &h(&t.s), &h(&t.s_prime), &h(&t.r_pub),
        );
        assert_eq!(hex::encode(e), t.e, "schnorr[{i}] challenge");
        // generate: byte-exact R33 ‖ S'33 ‖ z32 given the vector's nonce r
        let proof = schnorr_generate_proof(
            h(&t.a), h(&t.a_pub), h(&t.b_pub), h(&t.s), h(&t.r),
        )
        .unwrap();
        let expected = format!("{}{}{}", t.r_pub, t.s_prime, t.z);
        assert_eq!(hex::encode(&proof), expected, "schnorr[{i}] generate");
        // verify accepts
        assert!(
            schnorr_verify_proof(
                h(&t.a_pub), h(&t.b_pub), h(&t.s), h(&t.r_pub), h(&t.s_prime), h(&t.z),
            )
            .unwrap(),
            "schnorr[{i}] verify accept"
        );
    }
}

/// Schnorr reject class (issue #6): corrupted proofs the SDK rejects must be
/// rejected natively too (verdict parity — all fields well-formed by design).
#[test]
fn schnorr_reject_vectors_match() {
    let v = load();
    assert!(!v.schnorr_reject.is_empty());
    for (i, t) in v.schnorr_reject.iter().enumerate() {
        assert!(
            !schnorr_verify_proof(
                h(&t.a_pub), h(&t.b_pub), h(&t.s), h(&t.r_pub), h(&t.s_prime), h(&t.z),
            )
            .unwrap(),
            "schnorrReject[{i}] ({}) was ACCEPTED",
            t.label
        );
    }
}

/// Tweak class: (k+t) mod n and P+t·G byte-exact vs SDK BigNumber/Point math.
#[test]
fn tweak_vectors_exact_match() {
    let v = load();
    assert!(!v.tweak.is_empty());
    for (i, t) in v.tweak.iter().enumerate() {
        let priv_r = privkey_tweak_add(h(&t.privkey), h(&t.tweak)).unwrap();
        assert_eq!(hex::encode(&priv_r), t.priv_result, "tweak[{i}] priv");
        let pub_r = pubkey_tweak_add(h(&t.pubkey), h(&t.tweak)).unwrap();
        assert_eq!(hex::encode(&pub_r), t.pub_result, "tweak[{i}] pub");
    }
}

// ═══ M3 Tier-2 classes (issues #8/#9 — batch flows + uncompressed outputs) ═══

/// batchSign class: batch_ecdsa_sign over the whole vector set in ONE call must
/// produce, per element, the SDK's DER (forceLowS RFC 6979) AND the SDK's
/// compressed pubkey — i.e. the framed [derLen][der][pubkey33] layout carries
/// exactly ecdsa_sign(msg_i, key_i) ‖ pubkey_create(key_i).
#[test]
fn batch_sign_vectors_exact_match() {
    let v = load();
    assert!(!v.batch_sign.is_empty());
    let mut msgs = Vec::new();
    let mut keys = Vec::new();
    for t in &v.batch_sign {
        msgs.extend_from_slice(&h(&t.msg32));
        keys.extend_from_slice(&h(&t.privkey));
    }
    let framed = batch_ecdsa_sign(msgs, keys).unwrap();
    let mut off = 0usize;
    for (i, t) in v.batch_sign.iter().enumerate() {
        let len = framed[off] as usize;
        let der = &framed[off + 1..off + 1 + len];
        let pk = &framed[off + 1 + len..off + 1 + len + 33];
        assert_eq!(hex::encode(der), t.der, "batchSign[{i}] der");
        assert_eq!(hex::encode(pk), t.pubkey, "batchSign[{i}] pubkey");
        off += 1 + len + 33;
    }
    assert_eq!(off, framed.len(), "batchSign framing consumed exactly");
}

/// batchVerify class: batch_ecdsa_verify verdicts must equal the SDK's verify
/// verdict per element for both the all-valid and the corrupted sets.
#[test]
fn batch_verify_vectors_match() {
    let v = load();
    for (set_name, set) in [("valid", &v.batch_verify.valid), ("corrupted", &v.batch_verify.corrupted)] {
        assert!(!set.is_empty());
        let mut msgs = Vec::new();
        let mut sigs = Vec::new();
        let mut pubs = Vec::new();
        for t in set.iter() {
            msgs.extend_from_slice(&h(&t.msg32));
            let der = h(&t.der);
            sigs.push(der.len() as u8);
            sigs.extend_from_slice(&der);
            pubs.extend_from_slice(&h(&t.pubkey));
        }
        let verdicts = batch_ecdsa_verify(msgs, sigs, pubs).unwrap();
        for (i, t) in set.iter().enumerate() {
            assert_eq!(verdicts[i] == 1, t.valid, "batchVerify {set_name}[{i}]");
        }
    }
}

/// batchDerive class: ONE root + ONE counterparty + N invoices. The priv-side
/// batch must equal PrivateKey.deriveChild per element; the pub-side
/// uncompressed batch must equal PublicKey.deriveChild(...).encode(false).
#[test]
fn batch_derive_vectors_exact_match() {
    let v = load();
    let d = &v.batch_derive;
    assert!(!d.invoice_numbers.is_empty());
    let privs = batch_brc42_derive_child(
        h(&d.root),
        h(&d.counterparty_pub),
        d.invoice_numbers.clone(),
    )
    .unwrap();
    let pubs = batch_brc42_derive_child_pub_uncompressed(
        h(&d.counterparty_priv),
        h(&d.root_pub),
        d.invoice_numbers.clone(),
    )
    .unwrap();
    for (i, _) in d.invoice_numbers.iter().enumerate() {
        assert_eq!(
            hex::encode(&privs[i * 32..(i + 1) * 32]),
            d.derived_privs[i],
            "batchDerive priv[{i}]"
        );
        assert_eq!(
            hex::encode(&pubs[i * 65..(i + 1) * 65]),
            d.derived_pubs_uncompressed[i],
            "batchDerive pub[{i}]"
        );
        // element-wise equality with the proven single-op composites
        assert_eq!(
            privs[i * 32..(i + 1) * 32].to_vec(),
            brc42_derive_child(h(&d.root), h(&d.counterparty_pub), d.invoice_numbers[i].clone())
                .unwrap(),
            "batchDerive priv[{i}] == per-op"
        );
        assert_eq!(
            pubs[i * 65..(i + 1) * 65].to_vec(),
            brc42_derive_child_pub_uncompressed(
                h(&d.counterparty_priv),
                h(&d.root_pub),
                d.invoice_numbers[i].clone()
            )
            .unwrap(),
            "batchDerive pub[{i}] == per-op"
        );
    }
}

/// uncompressed class: every *_uncompressed variant must equal the SDK's
/// encode(false) output byte-for-byte (0x04‖x‖y — no JS decompression needed).
#[test]
fn uncompressed_vectors_exact_match() {
    let v = load();
    let u = &v.uncompressed;
    assert_eq!(
        hex::encode(pubkey_create_uncompressed(h(&u.privkey)).unwrap()),
        u.pubkey_create,
        "pubkey_create_uncompressed"
    );
    assert_eq!(
        hex::encode(ecdh_shared_point_uncompressed(h(&u.privkey), h(&u.pubkey)).unwrap()),
        u.ecdh_shared_point,
        "ecdh_shared_point_uncompressed"
    );
    assert_eq!(
        hex::encode(pubkey_tweak_add_uncompressed(h(&u.pubkey), h(&u.tweak)).unwrap()),
        u.tweak_add,
        "pubkey_tweak_add_uncompressed"
    );
    assert_eq!(
        hex::encode(ecdsa_recover_uncompressed(h(&u.msg32), h(&u.compact)).unwrap()),
        u.recovered,
        "ecdsa_recover_uncompressed"
    );
}
