// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(engine_nativeFFI)
import engine_nativeFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_engine_native_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_engine_native_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * The failure modes of the seam (design doc §3). Bytes-only boundary — the
 * caller falls back per-op to the pure-JS path on ANY error (M3 contract).
 * Fielded uniffi error: Swift sees typed cases; the Nitro layer rethrows and
 * the JS seam treats any rejection as "fall back".
 */
public enum EngineError {

    
    
    case BadFraming
    case TxParse
    case NotP2pkh(inputIndex: UInt32
    )
    case UnsupportedScope(inputIndex: UInt32
    )
    case IndexOutOfRange
    case BeefInvalid
    case Crypto(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineError: FfiConverterRustBuffer {
    typealias SwiftType = EngineError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .BadFraming
        case 2: return .TxParse
        case 3: return .NotP2pkh(
            inputIndex: try FfiConverterUInt32.read(from: &buf)
            )
        case 4: return .UnsupportedScope(
            inputIndex: try FfiConverterUInt32.read(from: &buf)
            )
        case 5: return .IndexOutOfRange
        case 6: return .BeefInvalid
        case 7: return .Crypto(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EngineError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .BadFraming:
            writeInt(&buf, Int32(1))
        
        
        case .TxParse:
            writeInt(&buf, Int32(2))
        
        
        case let .NotP2pkh(inputIndex):
            writeInt(&buf, Int32(3))
            FfiConverterUInt32.write(inputIndex, into: &buf)
            
        
        case let .UnsupportedScope(inputIndex):
            writeInt(&buf, Int32(4))
            FfiConverterUInt32.write(inputIndex, into: &buf)
            
        
        case .IndexOutOfRange:
            writeInt(&buf, Int32(5))
        
        
        case .BeefInvalid:
            writeInt(&buf, Int32(6))
        
        
        case let .Crypto(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension EngineError: Equatable, Hashable {}

extension EngineError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}
/**
 * Signs all P2PKH inputs described by `inputs_meta` against `unsigned_tx`
 * (outpoints + sequences are read from the tx itself — single source of
 * truth; the tx's input scripts are ignored).
 *
 * `inputs_meta`: N fixed 73-byte records
 * `[u32 LE inputIndex][32B privkey][u64 LE satoshis][u32 LE sigScope][25B P2PKH lockingScript]`
 *
 * Returns framed per-record, same order as the meta:
 * `[u32 LE inputIndex][u8 len][unlockingScript]`
 * where unlockingScript = `push(DER‖scopeByte) push(pubkey33)` — byte-identical
 * to the SDK P2PKH template's `UnlockingScript` for the same input (proven:
 * 200k-case M5.3 gate on the spike + spike-parity test + drift sample here).
 *
 * ECDSA core: libsecp256k1 (`SECP256K1.sign_ecdsa` — RFC 6979, always low-S),
 * the ratified #19 sign path. DER bytes equal the SDK's
 * `sig.toDER()‖scopeByte` (`toChecksigFormat`) exactly.
 *
 * Reject-on-any-invalid-element: any bad record fails the WHOLE call and the
 * caller falls back to the pure-JS path for the whole tx.
 */
public func batchSignP2pkhInputs(unsignedTx: Data, inputsMeta: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeEngineError.lift) {
    uniffi_engine_native_fn_func_batch_sign_p2pkh_inputs(
        FfiConverterData.lower(unsignedTx),
        FfiConverterData.lower(inputsMeta),$0
    )
})
}
/**
 * Verifies all P2PKH inputs of one SIGNED tx against their prevout satoshis +
 * locking scripts — ONE crossing for the whole tx, replacing the toolbox
 * `verifyUnlockScripts` per-input fresh-`Spend` interpreter + n sync ECDSA
 * crossings (docs/TIER3-ENGINE-DESIGN.md §M5.B; consumes the batchEcdsaVerify
 * debt, caveat A7).
 *
 * `prevouts_meta`: N fixed 37-byte records
 * `[u32 LE inputIndex][u64 LE satoshis][25B P2PKH lockingScript]`
 * (outpoints/sequences/version and every input's unlocking script are read
 * from `signed_tx` — single source of truth).
 *
 * Returns a per-record verdict byte in meta order: `0x01` valid, `0x00`
 * invalid. The verdict for each input equals the SDK `Spend` interpreter's
 * default-flags CHECKSIG result (see `verify_one`), so byte-for-byte
 * shadow-mode comparison against the JS verdict is meaningful.
 *
 * MANDATORY P2PKH shape (never silently weaken validation, design doc §3):
 * each input's unlocking script must be exactly `push(sig‖scopeByte)
 * push(33B pubkey)` with `hash160(pubkey) == lock pkh` and the sigScope byte a
 * supported FORKID/non-CHRONICLE scope; ANY input failing this fails the WHOLE
 * call (`Err(NotP2pkh{i})` / `Err(UnsupportedScope{i})`) and the caller runs
 * the full JS `Spend` on the tx. Reject-on-any-invalid mirrors the sign path.
 */
public func batchVerifyP2pkhInputs(signedTx: Data, prevoutsMeta: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeEngineError.lift) {
    uniffi_engine_native_fn_func_batch_verify_p2pkh_inputs(
        FfiConverterData.lower(signedTx),
        FfiConverterData.lower(prevoutsMeta),$0
    )
})
}
/**
 * BEEF → Extended Format (BRC-30) conversion (design doc §M5.C), replacing the
 * `services/arcadeBroadcastProvider.ts` serialize→reparse→toEF round-trip. The
 * output is byte-identical to the SDK's `Transaction.fromBEEF(beef, txid).toEF()`
 * (proven: the M5.9 `beef` fuzz class vs the app's patched @bsv/sdk@2.1.6, plus
 * the tx-003→tx-004 conformance anchor below).
 *
 * `txid`: the subject transaction, in INTERNAL byte order (32 bytes) — JS
 * converts at the hex boundary, per the seam convention. An EMPTY `txid`
 * selects the subject the way the SDK's `fromAnyBeef` does:
 * `atomic_txid ?? last tx`.
 *
 * READ-ONLY: this reads the BEEF and emits EF; it never re-emits BEEF.
 *
 * `Err(BeefInvalid)` on parse failure, unknown/absent subject txid, a
 * txid-only subject, or any missing ancestry that leaves an input without the
 * source output `to_ef` requires. `Err(BadFraming)` if `txid` is a non-empty
 * wrong length.
 */
public func beefToEf(beef: Data, txid: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeEngineError.lift) {
    uniffi_engine_native_fn_func_beef_to_ef(
        FfiConverterData.lower(beef),
        FfiConverterData.lower(txid),$0
    )
})
}
/**
 * Structural BEEF verification (design doc §M5.C): parse + `verify_valid`, then
 * return the per-block-height merkle roots for the caller's JS
 * `chainTracker.isValidRootForHeight` step. A "BEEF verified" claim is
 * structural + roots + the JS-checked headers — never structural alone; this
 * fn delivers only the first two.
 *
 * `allow_txid_only = false`: the internalizeAction / EF-conversion contract
 * requires a fully-hydrated BEEF (no txid-only leaves), the strictest verdict.
 * The oracle compares against the SDK `Beef.isValid(false)` under the same rule.
 *
 * Returns, on a structurally-valid BEEF, roots framed in ASCENDING block height
 * for determinism (design doc §3 shape):
 * `[u32 LE count]([u32 LE blockHeight][32B merkleRoot, display order])*`
 * The merkle root bytes are display order (the `MerklePath::compute_root` hex
 * string decoded as-is — the same order a block header carries), so JS hands
 * them straight to the chain tracker without a byte reversal.
 *
 * `Err(BeefInvalid)` on any parse failure OR `verify_valid` = false — the
 * single verdict the SDK's `isValid` boolean maps to. READ-ONLY: no
 * re-serialization occurs.
 */
public func beefVerifyStructure(beef: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeEngineError.lift) {
    uniffi_engine_native_fn_func_beef_verify_structure(
        FfiConverterData.lower(beef),$0
    )
})
}
/**
 * Conformance/debug export (design doc §1): one sighash, **signing order
 * only** (internal byte order, ready for ECDSA). Never routed in prod.
 */
public func computeSighashSigningOrder(rawTx: Data, inputIndex: UInt32, subscriptScript: Data, satoshis: UInt64, scope: UInt32)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeEngineError.lift) {
    uniffi_engine_native_fn_func_compute_sighash_signing_order(
        FfiConverterData.lower(rawTx),
        FfiConverterUInt32.lower(inputIndex),
        FfiConverterData.lower(subscriptScript),
        FfiConverterUInt64.lower(satoshis),
        FfiConverterUInt32.lower(scope),$0
    )
})
}
/**
 * Trivial FFI smoke fn (issue #19 exit proof): echoes the payload back
 * unchanged. Exercises the whole ArrayBuffer → Data → RustBuffer → Vec<u8>
 * round-trip without touching any crypto.
 */
public func enginePing(payload: Data) -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_engine_native_fn_func_engine_ping(
        FfiConverterData.lower(payload),$0
    )
})
}
/**
 * Probe + proof-artifact stamping (design doc §3 shape:
 * `"bsv-rs <hash> / engine-ffi <version>"` + the ratified sign core).
 */
public func engineVersion() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_engine_native_fn_func_engine_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_engine_native_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_engine_native_checksum_func_batch_sign_p2pkh_inputs() != 25308) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_native_checksum_func_batch_verify_p2pkh_inputs() != 3483) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_native_checksum_func_beef_to_ef() != 49880) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_native_checksum_func_beef_verify_structure() != 679) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_native_checksum_func_compute_sighash_signing_order() != 22453) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_native_checksum_func_engine_ping() != 62325) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_native_checksum_func_engine_version() != 22386) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all