// swift-tools-version:5.9
// Generated by scripts/build-secp-xcframework.sh — do not edit by hand.
import PackageDescription

let package = Package(
    name: "SecpNativeFFI",
    platforms: [ .iOS(.v15) ],
    products: [ .library(name: "SecpNative", targets: ["SecpNative"]) ],
    targets: [
        .binaryTarget(name: "SecpNativeFFI", path: "SecpNative.xcframework"),
        .target(name: "SecpNative", dependencies: ["SecpNativeFFI"], path: "Sources/SecpNative")
    ]
)
