// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(secp_nativeFFI)
import secp_nativeFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_secp_native_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_secp_native_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * The failure modes the FFI surfaces. Bytes-only across the boundary — messages are
 * human strings, no secp256k1 type ever crosses.
 */
public enum SecpError {

    
    
    case InvalidInput(String
    )
    case Crypto(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSecpError: FfiConverterRustBuffer {
    typealias SwiftType = SecpError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SecpError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidInput(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .Crypto(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SecpError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidInput(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Crypto(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension SecpError: Equatable, Hashable {}

extension SecpError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
/**
 * Batch BRC-42 PRIVATE-side deriveChild — ONE crossing for a whole flow's
 * derivations against one counterparty. The ECDH shared point depends only on
 * (root, counterparty) and is computed once; per invoice: HMAC + (k + t) mod n.
 * Output: N×32 child private keys, cat. Element i == brc42_derive_child(root,
 * counterparty, invoice_i) byte-for-byte.
 */
public func batchBrc42DeriveChild(privkey32: Data, counterpartyPubkey33: Data, invoiceNumbers: [String])throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_batch_brc42_derive_child(
        FfiConverterData.lower(privkey32),
        FfiConverterData.lower(counterpartyPubkey33),
        FfiConverterSequenceString.lower(invoiceNumbers),$0
    )
})
}
/**
 * Batch BRC-42 PUBLIC-side deriveChild, uncompressed — ONE crossing for a whole
 * flow's output-key derivations against one counterparty. Output: N×65 cat.
 * Element i == brc42_derive_child_pub_uncompressed(priv, pub, invoice_i).
 */
public func batchBrc42DeriveChildPubUncompressed(privkey32: Data, pubkey33: Data, invoiceNumbers: [String])throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_batch_brc42_derive_child_pub_uncompressed(
        FfiConverterData.lower(privkey32),
        FfiConverterData.lower(pubkey33),
        FfiConverterSequenceString.lower(invoiceNumbers),$0
    )
})
}
/**
 * Batch ECDSA sign — ONE crossing for a whole transaction's inputs.
 * Inputs: N×32 message digests and N×32 private keys, concatenated.
 * Output, per element: [1-byte derLen][DER signature][33-byte compressed pubkey].
 * Each element is EXACTLY ecdsa_sign(msg_i, key_i) ‖ pubkey_create(key_i); any
 * invalid element errors the whole call (seam falls back to the per-op path).
 */
public func batchEcdsaSign(msgs32Cat: Data, privkeys32Cat: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_batch_ecdsa_sign(
        FfiConverterData.lower(msgs32Cat),
        FfiConverterData.lower(privkeys32Cat),$0
    )
})
}
/**
 * Batch ECDSA verify — ONE crossing for a whole BEEF/SPV check set.
 * Inputs: N×32 digests cat, sigs framed per element as [1-byte derLen][DER],
 * N×33 compressed pubkeys cat. Output: N bytes, 1 = valid, 0 = invalid.
 * Element semantics identical to ecdsa_verify (S normalized first); malformed
 * framing/sig/pubkey errors the whole call (seam falls back to per-op).
 */
public func batchEcdsaVerify(msgs32Cat: Data, sigsFramed: Data, pubkeys33Cat: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_batch_ecdsa_verify(
        FfiConverterData.lower(msgs32Cat),
        FfiConverterData.lower(sigsFramed),
        FfiConverterData.lower(pubkeys33Cat),$0
    )
})
}
/**
 * BRC-42 deriveChild (the composite the Nitro module will actually serve):
 * sharedPoint = compress(privkey · counterpartyPub)
 * tweak       = HMAC-SHA256(key = sharedPoint33, msg = utf8(invoiceNumber))
 * child       = (privkey + tweak) mod n
 * Byte-exact vs @bsv/sdk PrivateKey.deriveChild (nonce-free — no RFC 6979 involved).
 */
public func brc42DeriveChild(privkey32: Data, counterpartyPubkey33: Data, invoiceNumber: String)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_brc42_derive_child(
        FfiConverterData.lower(privkey32),
        FfiConverterData.lower(counterpartyPubkey33),
        FfiConverterString.lower(invoiceNumber),$0
    )
})
}
/**
 * BRC-42 PUBLIC-side deriveChild composite, uncompressed output:
 * shared = compress(privkey · pubkey)
 * tweak  = HMAC-SHA256(key = shared33, msg = utf8(invoiceNumber))
 * child  = pubkey + tweak·G   (65-byte 0x04‖x‖y)
 * Equals @bsv/sdk PublicKey.deriveChild(privateKey, invoiceNumber).encode(false)
 * byte-for-byte (nonce-free).
 */
public func brc42DeriveChildPubUncompressed(privkey32: Data, pubkey33: Data, invoiceNumber: String)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_brc42_derive_child_pub_uncompressed(
        FfiConverterData.lower(privkey32),
        FfiConverterData.lower(pubkey33),
        FfiConverterString.lower(invoiceNumber),$0
    )
})
}
/**
 * ECDH shared POINT, compressed 33 bytes — NOT hashed. BRC-42 keys its HMAC with the
 * raw compressed shared point (@bsv/sdk: `sharedSecret.encode(true)` where
 * sharedSecret = counterpartyPub.mulCT(priv)). We use secp256k1::ecdh::shared_secret_point
 * (the un-hashed x||y variant of ECDH) and compress: prefix 0x02/0x03 by y parity + x.
 */
public func ecdhSharedPoint(privkey32: Data, pubkey33: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_ecdh_shared_point(
        FfiConverterData.lower(privkey32),
        FfiConverterData.lower(pubkey33),$0
    )
})
}
/**
 * 65-byte ECDH shared POINT — decompressed `ecdh_shared_point` (NOT hashed).
 */
public func ecdhSharedPointUncompressed(privkey32: Data, pubkey33: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_ecdh_shared_point_uncompressed(
        FfiConverterData.lower(privkey32),
        FfiConverterData.lower(pubkey33),$0
    )
})
}
/**
 * ECDSA public-key recovery from a 65-byte SDK compact signature
 * (`Signature.toCompact` layout: [compactByte 27..=34, r32, s32] — 27..31 =
 * uncompressed flag, 31..35 = compressed; recovery id = (compactByte - 27) & 3,
 * exactly `PublicKey.fromMsgHashAndCompactSignature`). Returns the compressed
 * 33-byte public key. Byte-exact vs @bsv/sdk for recid 0/1; see the module note
 * above for the recid-2/3 field-overflow asymmetry (native rejects, seam falls
 * back to JS).
 */
public func ecdsaRecover(msg32: Data, compact65: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_ecdsa_recover(
        FfiConverterData.lower(msg32),
        FfiConverterData.lower(compact65),$0
    )
})
}
/**
 * 65-byte recovered public key — decompressed `ecdsa_recover` (same compact65
 * layout and same recid-2/3 field-overflow rejection → JS fallback at the seam).
 */
public func ecdsaRecoverUncompressed(msg32: Data, compact65: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_ecdsa_recover_uncompressed(
        FfiConverterData.lower(msg32),
        FfiConverterData.lower(compact65),$0
    )
})
}
/**
 * Recovery-factor search — `Signature.CalculateRecoveryFactor` semantics: try
 * recids 0..=3 in order, return the first whose recovered key equals `pubkey33`,
 * error when none matches (the SDK throws 'Unable to find valid recovery factor').
 * `sig64` is r32 ‖ s32 (the compact signature without the recovery byte).
 */
public func ecdsaRecoveryFactor(msg32: Data, sig64: Data, pubkey33: Data)throws  -> UInt32 {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_ecdsa_recovery_factor(
        FfiConverterData.lower(msg32),
        FfiConverterData.lower(sig64),
        FfiConverterData.lower(pubkey33),$0
    )
})
}
/**
 * ECDSA sign over a 32-byte message digest (the caller hashes; this NEVER hashes).
 * Returns the DER-encoded signature. libsecp256k1 uses RFC 6979 deterministic nonces
 * and always yields low-S — matching @bsv/sdk ECDSA.sign(..., forceLowS=true) byte-for-byte.
 */
public func ecdsaSign(msg32: Data, privkey32: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_ecdsa_sign(
        FfiConverterData.lower(msg32),
        FfiConverterData.lower(privkey32),$0
    )
})
}
/**
 * ECDSA verify: 32-byte digest, DER signature, 33-byte compressed pubkey.
 * Returns Ok(false) on a well-formed-but-invalid signature; Err only on malformed inputs.
 * NOTE: libsecp256k1 verification REJECTS high-S signatures (BIP-146 strictness); we
 * normalize S first so verification semantics match @bsv/sdk's verify (which accepts
 * any s in [1, n-1]).
 */
public func ecdsaVerify(msg32: Data, derSig: Data, pubkey33: Data)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_ecdsa_verify(
        FfiConverterData.lower(msg32),
        FfiConverterData.lower(derSig),
        FfiConverterData.lower(pubkey33),$0
    )
})
}
/**
 * (k + t) mod n — the private half of BRC-42 child derivation
 * (@bsv/sdk PrivateKey.deriveChild: `this.add(new BigNumber(hmac)).mod(curve.n)`).
 */
public func privkeyTweakAdd(privkey32: Data, tweak32: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_privkey_tweak_add(
        FfiConverterData.lower(privkey32),
        FfiConverterData.lower(tweak32),$0
    )
})
}
/**
 * P + Q — compressed in, compressed out (@bsv/sdk Point.add, incl. P == Q
 * doubling). P + (-P) (the infinity result) is an error here, matching the app
 * seam's fallback contract (the SDK returns the infinity point).
 */
public func pubkeyCombine(pubkey33A: Data, pubkey33B: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_pubkey_combine(
        FfiConverterData.lower(pubkey33A),
        FfiConverterData.lower(pubkey33B),$0
    )
})
}
/**
 * Compressed (33-byte) public key for a 32-byte private key.
 */
public func pubkeyCreate(privkey32: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_pubkey_create(
        FfiConverterData.lower(privkey32),$0
    )
})
}
/**
 * 65-byte 0x04‖x‖y public key for a private key — decompressed `pubkey_create`.
 */
public func pubkeyCreateUncompressed(privkey32: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_pubkey_create_uncompressed(
        FfiConverterData.lower(privkey32),$0
    )
})
}
/**
 * P + t·G — compressed in, compressed out. The public half of BRC-42 child derivation.
 */
public func pubkeyTweakAdd(pubkey33: Data, tweak32: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_pubkey_tweak_add(
        FfiConverterData.lower(pubkey33),
        FfiConverterData.lower(tweak32),$0
    )
})
}
/**
 * 65-byte P + t·G — decompressed `pubkey_tweak_add`.
 */
public func pubkeyTweakAddUncompressed(pubkey33: Data, tweak32: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_pubkey_tweak_add_uncompressed(
        FfiConverterData.lower(pubkey33),
        FfiConverterData.lower(tweak32),$0
    )
})
}
/**
 * t·P — compressed in, compressed out (@bsv/sdk Point.mul with a scalar in
 * [1, n-1]). libsecp rejects t = 0 and t >= n (the SDK reduces mod n / returns
 * infinity) — callers pre-reduce JS-side; out-of-range input here is an error.
 */
public func pubkeyTweakMul(pubkey33: Data, scalar32: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_pubkey_tweak_mul(
        FfiConverterData.lower(pubkey33),
        FfiConverterData.lower(scalar32),$0
    )
})
}
/**
 * @bsv/sdk Schnorr.generateProof (ZK proof of DH shared secret, NOT BIP-340)
 * with the nonce r as an explicit parameter (the SDK draws it internally from
 * PrivateKey.fromRandom; the JS seam does the same and passes it in):
 * R = r·G,  S' = r·B,  e = challenge(A, B, S, S', R),  z = (r + e·a) mod n
 * Returns R33 ‖ S'33 ‖ z32 (98 bytes), byte-exact vs the SDK given the same r.
 * A is a parameter (not derived from a) because the SDK hashes the CALLER's A.
 */
public func schnorrGenerateProof(a32: Data, aPub33: Data, bPub33: Data, sPoint33: Data, r32: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_schnorr_generate_proof(
        FfiConverterData.lower(a32),
        FfiConverterData.lower(aPub33),
        FfiConverterData.lower(bPub33),
        FfiConverterData.lower(sPoint33),
        FfiConverterData.lower(r32),$0
    )
})
}
/**
 * @bsv/sdk Schnorr.verifyProof:
 * e = challenge(A, B, S, S', R);  valid ⇔ z·G == R + e·A  AND  z·B == S' + e·S
 * z must be in [1, n-1]. The seam routes ONLY in-range z and falls back to pure
 * JS otherwise — measured fact (fuzz probe schnorr_z_ge_n + direct host test):
 * the SDK's Point.mul is NOT consistently (z mod n)·G for out-of-range scalars
 * (g.mul(n+1) matches the reduced value but g.mul(2^256-1) does not), so
 * pre-reducing would CHANGE the SDK's verdict for adversarial z; only the JS
 * fallback preserves it. z = 0 is likewise an error → JS fallback (the SDK
 * compares against the infinity point there). An infinity sum on the
 * right-hand side (combine error) is a defined FALSE, exactly like the SDK's
 * eq() against a finite left side.
 */
public func schnorrVerifyProof(aPub33: Data, bPub33: Data, sPoint33: Data, rPoint33: Data, sPrime33: Data, z32: Data)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeSecpError.lift) {
    uniffi_secp_native_fn_func_schnorr_verify_proof(
        FfiConverterData.lower(aPub33),
        FfiConverterData.lower(bPub33),
        FfiConverterData.lower(sPoint33),
        FfiConverterData.lower(rPoint33),
        FfiConverterData.lower(sPrime33),
        FfiConverterData.lower(z32),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_secp_native_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_secp_native_checksum_func_batch_brc42_derive_child() != 59547) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_batch_brc42_derive_child_pub_uncompressed() != 28677) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_batch_ecdsa_sign() != 63390) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_batch_ecdsa_verify() != 39446) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_brc42_derive_child() != 3245) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_brc42_derive_child_pub_uncompressed() != 20768) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_ecdh_shared_point() != 20298) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_ecdh_shared_point_uncompressed() != 39372) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_ecdsa_recover() != 58744) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_ecdsa_recover_uncompressed() != 10283) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_ecdsa_recovery_factor() != 57241) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_ecdsa_sign() != 28930) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_ecdsa_verify() != 45964) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_privkey_tweak_add() != 8599) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_pubkey_combine() != 25115) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_pubkey_create() != 4359) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_pubkey_create_uncompressed() != 52952) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_pubkey_tweak_add() != 4046) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_pubkey_tweak_add_uncompressed() != 39330) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_pubkey_tweak_mul() != 56318) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_schnorr_generate_proof() != 14795) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_secp_native_checksum_func_schnorr_verify_proof() != 50378) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all